name: defactify
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9

  # PyTorch + CUDA (cambiar pytorch-cuda según la versión de CUDA del servidor)
  - pytorch=2.5.0
  - torchvision=0.20.0
  - pytorch-cuda=11.8

  # Data processing
  - numpy=2.0.2
  - pandas=2.2.3
  - pillow=9.4.0

  # ML
  - scikit-learn=1.5.2
  - scipy=1.13.1

  # Visualization
  - matplotlib=3.9.2

  # Utils
  - pyyaml=6.0.2
  - tqdm=4.66.5
  - opencv
  - click=8.1

  # Dev
  - jupyter
  - ipython
  - pytest

  # Pip
  - pip
  - pip:
      - datasets==3.0.1
      - transformers==4.57.6
      - safetensors==0.7.0
      - wandb==0.18.5
      - joblib==1.4.2
      - xgboost==2.1.1
      - tensorboard==2.20.0
